
[[constraint]]
  name = "github.com/cloudfoundry/bosh-cli"
  version = "3.0.1"

[[constraint]]
  name = "github.com/cloudfoundry/bosh-utils"
  revision = "fad7a5ad622c066cf1b36eb44b9612cec680e48c"
  packages = [
    "logger",
    "uuid"
  ]

[[constraint]]
  name = "github.com/cppforlife/go-patch"

[[constraint]]
  name = "github.com/mgutz/ansi"

[[constraint]]
  name = "github.com/onsi/ginkgo"

[[constraint]]
  name = "github.com/onsi/gomega"

[[constraint]]
  name = "github.com/pivotal-cf-experimental/cf-webmock"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.18.1"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/yaml.v1"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[prune]
  go-tests = true
  unused-packages = true
